<?php
declare(strict_types=1);

/**
 * mrl_unified_schedule_installer.php
 *
 * VERSION: v001
 * LAST MODIFIED: 8/18/2026 4:13:00 am
 *
 * DESCRIPTION:
 * TestPHP8-only installer that makes LP and RD use the same canonical
 * race schedule source:
 *
 *   /race_results/_race_results_schedule.json
 *
 * The canonical file is generated by race_results_monitor.php and contains
 * ESPN-derived MRL points-race identity and race start timing.
 *
 * THIS INSTALLER:
 * - Updates race_results/race_schedule_helper.php v002 -> v003.
 * - Updates team.php v017 -> v018 so RD deadlines use the shared helper.
 * - Updates race_results/race_results_rd_helper.php v003 -> v004 so RD
 *   effective-race selection also uses the shared canonical schedule helper.
 * - Removes LP/RD dependence on race_results/<year>/_schedule.json.
 * - Keeps segment_race_ranges as the DB source for segment boundaries.
 * - Makes no database schema or data changes.
 * - Creates timestamped backups before replacing any file.
 *
 * SAFETY:
 * - Refuses to run anywhere except testphp8.manliusracingleague.com.
 * - Requires the canonical /race_results/_race_results_schedule.json file.
 * - Validates expected source versions before install.
 * - Validates all transformations before any target file is replaced.
 * - Creates backups of all three target files before replacement.
 *
 * TARGET FILE VERSIONS BEFORE INSTALL:
 * - race_results/race_schedule_helper.php   v002
 * - team.php                                v017
 * - race_results/race_results_rd_helper.php v003
 *
 * TARGET FILE VERSIONS AFTER INSTALL:
 * - race_results/race_schedule_helper.php   v003
 * - team.php                                v018
 * - race_results/race_results_rd_helper.php v004
 *
 * CHANGELOG:
 * v001 (8/18/2026 4:13:00 am)
 * - Initial unified LP/RD schedule-source installer.
 */

date_default_timezone_set('America/New_York');

const INSTALLER_VERSION = 'v001';
const INSTALLER_TIMESTAMP = '20260818_041300am';
const REQUIRED_HOST = 'testphp8.manliusracingleague.com';

function h(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

function replace_once(string $content, string $old, string $new, string $label): string
{
    $count = substr_count($content, $old);
    if ($count !== 1) {
        throw new RuntimeException($label . ': expected exactly 1 source match, found ' . $count . '.');
    }
    return str_replace($old, $new, $content);
}

function atomic_write(string $path, string $content): void
{
    $dir = dirname($path);
    $tmp = $dir . '/.' . basename($path) . '.unified_schedule_' . bin2hex(random_bytes(5)) . '.tmp';

    if (file_put_contents($tmp, $content, LOCK_EX) === false) {
        throw new RuntimeException('Unable to write temporary file: ' . $tmp);
    }

    @chmod($tmp, 0644);

    if (!@rename($tmp, $path)) {
        @unlink($tmp);
        throw new RuntimeException('Unable to replace target file: ' . $path);
    }
}

function new_race_schedule_helper(): string
{
    return <<<'PHPFILE'
<?php
declare(strict_types=1);

/**
 * race_schedule_helper.php
 *
 * VERSION: v003
 * LAST MODIFIED: 8/18/2026 4:13:00 am
 *
 * DESCRIPTION:
 * Shared MRL race-schedule helper for LP and RD timing.
 *
 * Canonical race schedule source:
 * /race_results/_race_results_schedule.json
 *
 * Segment boundaries remain DB-driven from segment_race_ranges.
 *
 * CHANGELOG:
 *
 * v003 (8/18/2026 4:13:00 am)
 * - CHANGE: Replaced legacy /race_results/{year}/_schedule.json dependency with
 *   /race_results/_race_results_schedule.json.
 * - CHANGE: Uses mrl_points_races as the preferred canonical points-race list.
 * - NEW: Resolves segment boundaries from segment_race_ranges.
 * - NEW: Adds race-by-number and next-race-in-segment helpers shared by LP/RD.
 * - CHANGE: Race timing now uses canonical start_at/start_ts fields.
 * - CHANGE: Preserves existing LP function names/signatures for compatibility.
 *
 * v002 (3/31/2026)
 * - LP effective race now requires same-segment match.
 * - Returns null when no future points race remains in the active segment.
 * - Adds optional helper for fetching points races by segment.
 *
 * v001 (3/31/2026)
 * - Initial helper file.
 * - Loads canonical schedule JSON for a given year.
 * - Returns the first points race whose scheduled start time has not yet passed.
 * - Intended for LP logic only at this stage.
 */

const MRL_SCHEDULE_HELPER_TIMEZONE = 'America/New_York';

if (!function_exists('mrl_schedule_helper_timezone')) {
    function mrl_schedule_helper_timezone(): DateTimeZone
    {
        return new DateTimeZone(MRL_SCHEDULE_HELPER_TIMEZONE);
    }
}

if (!function_exists('mrl_schedule_helper_file_path')) {
    function mrl_schedule_helper_file_path(int $year): string
    {
        return __DIR__ . '/_race_results_schedule.json';
    }
}

if (!function_exists('mrl_schedule_helper_load')) {
    function mrl_schedule_helper_load(int $year): array
    {
        $file = mrl_schedule_helper_file_path($year);

        if (!is_file($file)) {
            throw new RuntimeException('Canonical race schedule file not found: ' . $file);
        }

        $json = file_get_contents($file);
        if ($json === false || trim($json) === '') {
            throw new RuntimeException('Canonical race schedule file could not be read or was empty: ' . $file);
        }

        $data = json_decode($json, true);
        if (!is_array($data)) {
            throw new RuntimeException('Canonical race schedule JSON is invalid: ' . $file);
        }

        if (isset($data['year']) && (int)$data['year'] !== $year) {
            throw new RuntimeException(
                'Canonical race schedule year mismatch. Expected ' . $year . ', found ' . (string)$data['year'] . '.'
            );
        }

        $hasMrlPoints = isset($data['mrl_points_races']) && is_array($data['mrl_points_races']);
        $hasRaces = isset($data['races']) && is_array($data['races']);

        if (!$hasMrlPoints && !$hasRaces) {
            throw new RuntimeException('Canonical race schedule JSON has no race list: ' . $file);
        }

        return $data;
    }
}

if (!function_exists('mrl_schedule_helper_race_number')) {
    function mrl_schedule_helper_race_number(array $race): int
    {
        $number = (int)($race['mrl_race_number'] ?? 0);
        if ($number <= 0) {
            $number = (int)($race['race_number'] ?? 0);
        }
        if ($number <= 0) {
            $number = (int)($race['schedule_sequence'] ?? 0);
        }

        return $number;
    }
}

if (!function_exists('mrl_schedule_helper_race_datetime')) {
    function mrl_schedule_helper_race_datetime(array $race): DateTimeImmutable
    {
        $startAt = trim((string)($race['start_at'] ?? ''));

        if ($startAt !== '') {
            $dt = DateTimeImmutable::createFromFormat(
                'Y-m-d H:i:s',
                $startAt,
                mrl_schedule_helper_timezone()
            );

            if ($dt instanceof DateTimeImmutable) {
                return $dt;
            }
        }

        $startTs = (int)($race['start_ts'] ?? 0);
        if ($startTs > 0) {
            return (new DateTimeImmutable('@' . $startTs))->setTimezone(mrl_schedule_helper_timezone());
        }

        throw new RuntimeException(
            'Race entry missing valid canonical start_at/start_ts for R'
            . str_pad((string)mrl_schedule_helper_race_number($race), 2, '0', STR_PAD_LEFT)
            . '.'
        );
    }
}

if (!function_exists('mrl_schedule_helper_points_races')) {
    function mrl_schedule_helper_points_races(int $year): array
    {
        $data = mrl_schedule_helper_load($year);

        if (isset($data['mrl_points_races']) && is_array($data['mrl_points_races'])) {
            $source = $data['mrl_points_races'];
        } else {
            $source = $data['races'];
        }

        $pointsRaces = [];

        foreach ($source as $race) {
            if (!is_array($race)) {
                continue;
            }

            if (!empty($race['is_exhibition'])) {
                continue;
            }

            if (array_key_exists('mrl_points_eligible', $race) && $race['mrl_points_eligible'] === false) {
                continue;
            }

            if ((int)($race['year'] ?? $year) !== $year) {
                continue;
            }

            $raceNumber = mrl_schedule_helper_race_number($race);
            if ($raceNumber <= 0) {
                continue;
            }

            $race['race_number'] = $raceNumber;
            if (!isset($race['mrl_race_number']) || (int)$race['mrl_race_number'] <= 0) {
                $race['mrl_race_number'] = $raceNumber;
            }

            $pointsRaces[] = $race;
        }

        usort($pointsRaces, function (array $a, array $b): int {
            return mrl_schedule_helper_race_number($a) <=> mrl_schedule_helper_race_number($b);
        });

        return $pointsRaces;
    }
}

if (!function_exists('mrl_schedule_helper_segment_bounds')) {
    function mrl_schedule_helper_segment_bounds(int $year, string $segment): array
    {
        $segment = strtoupper(trim($segment));
        if ($segment === '') {
            throw new RuntimeException('Segment is required for schedule lookup.');
        }

        global $dbo, $dbconnect;

        if (isset($dbo) && $dbo instanceof PDO) {
            $sql = "
                SELECT startRace, endRace
                FROM segment_race_ranges
                WHERE raceYear = :raceYear
                  AND segment = :segment
                LIMIT 1
            ";
            $stmt = $dbo->prepare($sql);
            $stmt->execute([
                ':raceYear' => $year,
                ':segment' => $segment,
            ]);
            $row = $stmt->fetch(PDO::FETCH_ASSOC);

            if (is_array($row)) {
                $start = (int)($row['startRace'] ?? 0);
                $end = (int)($row['endRace'] ?? 0);

                if ($start > 0 && $end >= $start) {
                    return ['start' => $start, 'end' => $end];
                }
            }
        }

        if (isset($dbconnect) && $dbconnect instanceof mysqli) {
            $sql = "
                SELECT startRace, endRace
                FROM segment_race_ranges
                WHERE raceYear = ?
                  AND segment = ?
                LIMIT 1
            ";
            $stmt = mysqli_prepare($dbconnect, $sql);

            if ($stmt) {
                mysqli_stmt_bind_param($stmt, 'is', $year, $segment);
                mysqli_stmt_execute($stmt);
                mysqli_stmt_bind_result($stmt, $startRace, $endRace);

                if (mysqli_stmt_fetch($stmt)) {
                    mysqli_stmt_close($stmt);

                    $start = (int)$startRace;
                    $end = (int)$endRace;
                    if ($start > 0 && $end >= $start) {
                        return ['start' => $start, 'end' => $end];
                    }
                } else {
                    mysqli_stmt_close($stmt);
                }
            }
        }

        throw new RuntimeException(
            'No segment_race_ranges row available for ' . $year . ' ' . $segment . '.'
        );
    }
}

if (!function_exists('mrl_schedule_helper_points_races_by_segment')) {
    function mrl_schedule_helper_points_races_by_segment(int $year, string $segment): array
    {
        $bounds = mrl_schedule_helper_segment_bounds($year, $segment);
        $all = mrl_schedule_helper_points_races($year);
        $filtered = [];

        foreach ($all as $race) {
            $raceNumber = mrl_schedule_helper_race_number($race);

            if ($raceNumber < (int)$bounds['start'] || $raceNumber > (int)$bounds['end']) {
                continue;
            }

            $race['segment'] = strtoupper(trim($segment));
            $filtered[] = $race;
        }

        return $filtered;
    }
}

if (!function_exists('mrl_schedule_helper_race_by_number')) {
    function mrl_schedule_helper_race_by_number(int $year, int $raceNumber): ?array
    {
        foreach (mrl_schedule_helper_points_races($year) as $race) {
            if (mrl_schedule_helper_race_number($race) === $raceNumber) {
                return $race;
            }
        }

        return null;
    }
}

if (!function_exists('mrl_schedule_helper_next_race_in_segment')) {
    function mrl_schedule_helper_next_race_in_segment(
        int $year,
        string $segment,
        int $afterRaceNumber
    ): ?array {
        foreach (mrl_schedule_helper_points_races_by_segment($year, $segment) as $race) {
            if (mrl_schedule_helper_race_number($race) > $afterRaceNumber) {
                return $race;
            }
        }

        return null;
    }
}

if (!function_exists('mrl_get_effective_race_for_lp')) {
    /**
     * Returns the first canonical MRL points race in the SAME DB-defined segment
     * whose scheduled start time has not yet passed.
     *
     * This is the LP effective race. Earlier races in the segment are already
     * missed and score 0. If no future race remains in the segment, null is returned.
     */
    function mrl_get_effective_race_for_lp(
        int $year,
        string $segment,
        ?DateTimeImmutable $now = null
    ): ?array {
        $now = $now ?? new DateTimeImmutable('now', mrl_schedule_helper_timezone());

        foreach (mrl_schedule_helper_points_races_by_segment($year, $segment) as $race) {
            $raceStart = mrl_schedule_helper_race_datetime($race);

            if ($raceStart >= $now) {
                $raceNumber = mrl_schedule_helper_race_number($race);

                return [
                    'year' => $year,
                    'race_number' => $raceNumber,
                    'segment' => strtoupper(trim($segment)),
                    'mrl_race_code' => (string)($race['mrl_race_code'] ?? ('R' . str_pad((string)$raceNumber, 2, '0', STR_PAD_LEFT))),
                    'mrl_race_name' => (string)($race['mrl_race_name'] ?? $race['race_name'] ?? ''),
                    'track_name' => (string)($race['track_name'] ?? ''),
                    'date' => (string)($race['mrl_race_date'] ?? ''),
                    'time_et' => (string)($race['time_text'] ?? ''),
                    'datetime_et' => $raceStart->format('Y-m-d H:i:s'),
                    'start_at' => (string)($race['start_at'] ?? $raceStart->format('Y-m-d H:i:s')),
                    'start_ts' => $raceStart->getTimestamp(),
                    'race_start_dt' => $raceStart,
                ];
            }
        }

        return null;
    }
}

if (!function_exists('mrl_is_race_missed_for_lp')) {
    function mrl_is_race_missed_for_lp(
        int $year,
        int $raceNumber,
        ?DateTimeImmutable $now = null
    ): bool {
        $now = $now ?? new DateTimeImmutable('now', mrl_schedule_helper_timezone());
        $race = mrl_schedule_helper_race_by_number($year, $raceNumber);

        if (!is_array($race)) {
            throw new RuntimeException('Race number not found in canonical schedule: ' . $raceNumber);
        }

        return mrl_schedule_helper_race_datetime($race) < $now;
    }
}
PHPFILE;
}

function patch_team_php(string $src): string
{
    $src = replace_once(
        $src,
        " * VERSION: v017\n * LAST MODIFIED: 8/18/2026 3:08:27 am\n",
        " * VERSION: v018\n * LAST MODIFIED: 8/18/2026 4:13:00 am\n",
        'team.php header'
    );

    $src = replace_once(
        $src,
        " * CHANGELOG:\n *\n * v017 (8/18/2026 3:08:27 am)\n",
        " * CHANGELOG:\n *\n * v018 (8/18/2026 4:13:00 am)\n * - CHANGE: RD deadline lookup now uses shared race_schedule_helper.php.\n * - CHANGE: LP and RD timing now share /race_results/_race_results_schedule.json.\n * - CHANGE: Removed team.php dependency on legacy race_results/<year>/_schedule.json.\n * - CHANGE: RD deadline lookup now respects DB-defined segment boundaries through the shared helper.\n * - CHANGE: Preserved automatic LP, SPECIAL_AUTH, normal-pick and RD routing behavior.\n *\n * v017 (8/18/2026 3:08:27 am)\n",
        'team.php changelog'
    );

    $old = <<<'OLD'
function teampage_schedule_rows(string $raceYear): array
{
    $path = __DIR__ . '/race_results/' . $raceYear . '/_schedule.json';
    if (!is_file($path)) {
        return [];
    }

    $json = @file_get_contents($path);
    if ($json === false || trim($json) === '') {
        return [];
    }

    $data = json_decode($json, true);
    if (!is_array($data)) {
        return [];
    }

    if (isset($data['races']) && is_array($data['races'])) {
        return $data['races'];
    }

    return $data;
}

function teampage_schedule_row_by_race_number(string $raceYear, int $raceNumber): ?array
{
    $rows = teampage_schedule_rows($raceYear);
    foreach ($rows as $row) {
        if (!is_array($row)) {
            continue;
        }
        if ((int)($row['race_number'] ?? 0) === $raceNumber) {
            return $row;
        }
    }

    return null;
}

function teampage_schedule_deadline_info(string $raceYear, string $raceFolderName): array
{
    $currentRaceNumber = teampage_rd_folder_race_number($raceFolderName);
    if ($currentRaceNumber <= 0) {
        return [];
    }

    $deadlineRaceNumber = $currentRaceNumber + 1;
    $row = teampage_schedule_row_by_race_number($raceYear, $deadlineRaceNumber);
    if (!is_array($row)) {
        return [];
    }

    $datetimeEt = trim((string)($row['datetime_et'] ?? ''));
    if ($datetimeEt === '') {
        return [];
    }

    try {
        $dt = new DateTime($datetimeEt, new DateTimeZone('America/New_York'));
    } catch (Throwable $e) {
        return [];
    }

    return [
        'deadline_race_number' => $deadlineRaceNumber,
        'deadline_race_code' => 'R' . str_pad((string)$deadlineRaceNumber, 2, '0', STR_PAD_LEFT),
        'deadline_timestamp' => $dt->getTimestamp(),
        'deadline_display' => $dt->format('n/j/Y g:i a') . ' ET',
        'deadline_datetime_et' => $datetimeEt,
    ];
}
OLD;

    $new = <<<'NEW'
function teampage_schedule_deadline_info(
    string $raceYear,
    string $segment,
    string $raceFolderName
): array {
    $currentRaceNumber = teampage_rd_folder_race_number($raceFolderName);
    if ($currentRaceNumber <= 0) {
        return [];
    }

    try {
        $row = mrl_schedule_helper_next_race_in_segment(
            (int)$raceYear,
            $segment,
            $currentRaceNumber
        );

        if (!is_array($row)) {
            return [];
        }

        $deadlineRaceNumber = mrl_schedule_helper_race_number($row);
        $dt = mrl_schedule_helper_race_datetime($row);

        return [
            'deadline_race_number' => $deadlineRaceNumber,
            'deadline_race_code' => (string)($row['mrl_race_code'] ?? ('R' . str_pad((string)$deadlineRaceNumber, 2, '0', STR_PAD_LEFT))),
            'deadline_timestamp' => $dt->getTimestamp(),
            'deadline_display' => $dt->format('n/j/Y g:i a') . ' ET',
            'deadline_datetime_et' => $dt->format('Y-m-d H:i:s'),
        ];
    } catch (Throwable $e) {
        return [];
    }
}
NEW;

    $src = replace_once($src, $old, $new, 'team.php RD schedule helper block');

    $oldDeadlineCall = <<<'OLD'
$deadlineInfo = teampage_schedule_deadline_info((string)$raceYear, (string)($rdPendingInfo['raceFolderName'] ?? ''));
OLD;

    $newDeadlineCall = <<<'NEW'
$deadlineInfo = teampage_schedule_deadline_info((string)$raceYear, $rdPendingSegment, (string)($rdPendingInfo['raceFolderName'] ?? ''));
NEW;

    $src = replace_once(
        $src,
        $oldDeadlineCall,
        $newDeadlineCall,
        'team.php RD deadline call'
    );

    return $src;
}

function patch_rd_helper(string $src): string
{
    $src = replace_once(
        $src,
        " * VERSION: v003\n * LAST MODIFIED: 4/3/2026 12:28:00 am\n",
        " * VERSION: v004\n * LAST MODIFIED: 8/18/2026 4:13:00 am\n",
        'race_results_rd_helper.php header'
    );

    $src = replace_once(
        $src,
        " * CHANGELOG:\n *\n * v003 (4/3/2026)\n",
        " * CHANGELOG:\n *\n * v004 (8/18/2026 4:13:00 am)\n * - CHANGE: RD next-effective-race lookup now uses race_schedule_helper.php.\n * - CHANGE: RD now shares /race_results/_race_results_schedule.json with LP.\n * - CHANGE: Next RD race must be a canonical MRL points race inside the DB-defined segment.\n * - CHANGE: Preserved existing RD eligibility detection and one-RD-per-season behavior.\n *\n * v003 (4/3/2026)\n",
        'race_results_rd_helper.php changelog'
    );

    $src = replace_once(
        $src,
        "const MRL_RD_TIMEZONE = 'America/New_York';\n",
        "const MRL_RD_TIMEZONE = 'America/New_York';\n\nrequire_once __DIR__ . '/race_schedule_helper.php';\n",
        'race_results_rd_helper.php shared helper include'
    );

    $old = <<<'OLD'
if (!function_exists('mrl_rd_next_race_in_segment')) {
    function mrl_rd_next_race_in_segment(PDO $dbo, int $raceYear, string $segment, int $raceNumber): ?int
    {
        $bounds = mrl_rd_get_segment_bounds($dbo, $raceYear, $segment);
        $nextRace = $raceNumber + 1;

        if ($nextRace > (int)$bounds['end']) {
            return null;
        }

        return $nextRace;
    }
}
OLD;

    $new = <<<'NEW'
if (!function_exists('mrl_rd_next_race_in_segment')) {
    function mrl_rd_next_race_in_segment(PDO $dbo, int $raceYear, string $segment, int $raceNumber): ?int
    {
        try {
            $nextRace = mrl_schedule_helper_next_race_in_segment(
                $raceYear,
                $segment,
                $raceNumber
            );

            if (!is_array($nextRace)) {
                return null;
            }

            $nextRaceNumber = mrl_schedule_helper_race_number($nextRace);
            return ($nextRaceNumber > 0) ? $nextRaceNumber : null;
        } catch (Throwable $e) {
            return null;
        }
    }
}
NEW;

    $src = replace_once($src, $old, $new, 'race_results_rd_helper.php next-race logic');

    return $src;
}

function validate_canonical_schedule(string $path): array
{
    if (!is_file($path)) {
        throw new RuntimeException('Canonical schedule missing: ' . $path);
    }

    $raw = file_get_contents($path);
    if ($raw === false || trim($raw) === '') {
        throw new RuntimeException('Canonical schedule is unreadable or empty: ' . $path);
    }

    $data = json_decode($raw, true);
    if (!is_array($data)) {
        throw new RuntimeException('Canonical schedule is invalid JSON: ' . $path);
    }

    if ((int)($data['year'] ?? 0) !== 2026) {
        throw new RuntimeException('Canonical schedule year is not 2026.');
    }

    $races = $data['mrl_points_races'] ?? null;
    if (!is_array($races) || count($races) < 30) {
        throw new RuntimeException('Canonical schedule does not contain a usable mrl_points_races list.');
    }

    $hasR27 = false;
    foreach ($races as $race) {
        if (!is_array($race)) {
            continue;
        }
        $rn = (int)($race['mrl_race_number'] ?? $race['race_number'] ?? 0);
        if ($rn === 27 && trim((string)($race['start_at'] ?? '')) !== '') {
            $hasR27 = true;
            break;
        }
    }

    if (!$hasR27) {
        throw new RuntimeException('Canonical schedule does not contain a timed R27 entry.');
    }

    return [
        'generated_at' => (string)($data['generated_at'] ?? ''),
        'source' => (string)($data['source'] ?? ''),
        'points_races' => count($races),
    ];
}

$host = strtolower((string)($_SERVER['HTTP_HOST'] ?? ''));
$host = preg_replace('/:\d+$/', '', $host);

$root = __DIR__;
$targets = [
    'race_results/race_schedule_helper.php' => [
        'path' => $root . '/race_results/race_schedule_helper.php',
        'expected' => 'VERSION: v002',
        'after' => 'VERSION: v003',
    ],
    'team.php' => [
        'path' => $root . '/team.php',
        'expected' => 'VERSION: v017',
        'after' => 'VERSION: v018',
    ],
    'race_results/race_results_rd_helper.php' => [
        'path' => $root . '/race_results/race_results_rd_helper.php',
        'expected' => 'VERSION: v003',
        'after' => 'VERSION: v004',
    ],
];

$canonicalSchedule = $root . '/race_results/_race_results_schedule.json';
$backupDir = $root . '/mrl_unified_schedule_backup_' . INSTALLER_TIMESTAMP;

$errors = [];
$prepared = [];
$scheduleInfo = [];

if ($host !== REQUIRED_HOST) {
    $errors[] = 'REFUSED: installer may run only on ' . REQUIRED_HOST . '. Current host: ' . ($host !== '' ? $host : '(unknown)');
}

try {
    $scheduleInfo = validate_canonical_schedule($canonicalSchedule);
} catch (Throwable $e) {
    $errors[] = $e->getMessage();
}

foreach ($targets as $label => $meta) {
    $path = $meta['path'];

    if (!is_file($path)) {
        $errors[] = $label . ': file not found.';
        continue;
    }

    if (!is_readable($path)) {
        $errors[] = $label . ': file is not readable.';
        continue;
    }

    if (!is_writable($path)) {
        $errors[] = $label . ': file is not writable.';
        continue;
    }

    $src = file_get_contents($path);
    if ($src === false) {
        $errors[] = $label . ': unable to read file.';
        continue;
    }

    if (strpos($src, $meta['expected']) === false) {
        $errors[] = $label . ': expected source version not found (' . $meta['expected'] . ').';
        continue;
    }

    try {
        if ($label === 'race_results/race_schedule_helper.php') {
            $new = new_race_schedule_helper();
        } elseif ($label === 'team.php') {
            $new = patch_team_php($src);
        } else {
            $new = patch_rd_helper($src);
        }

        if (strpos($new, $meta['after']) === false) {
            throw new RuntimeException($label . ': transformed version marker not found.');
        }

        $prepared[$label] = [
            'path' => $path,
            'old' => $src,
            'new' => $new,
        ];
    } catch (Throwable $e) {
        $errors[] = $e->getMessage();
    }
}

$installRequested = ($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST'
    && isset($_POST['install_unified_schedule']);

$installed = false;
$installMessage = '';

if ($installRequested && empty($errors)) {
    try {
        if (!is_dir($backupDir) && !mkdir($backupDir, 0755, true)) {
            throw new RuntimeException('Unable to create backup folder: ' . $backupDir);
        }

        foreach ($prepared as $label => $row) {
            $backupPath = $backupDir . '/' . str_replace('/', '__', $label);
            if (file_put_contents($backupPath, $row['old'], LOCK_EX) === false) {
                throw new RuntimeException('Unable to create backup: ' . $backupPath);
            }
        }

        foreach ($prepared as $label => $row) {
            atomic_write($row['path'], $row['new']);
        }

        $installed = true;
        $installMessage = 'INSTALL COMPLETE: LP/RD now use /race_results/_race_results_schedule.json as the shared race schedule source. Backups saved in ' . basename($backupDir) . '.';
    } catch (Throwable $e) {
        $errors[] = 'INSTALL FAILED: ' . $e->getMessage();
    }
}

?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>MRL Unified LP/RD Schedule Installer</title>
<style>
body{background:#0f141a;color:#eef4ff;font-family:Arial,sans-serif;margin:0;padding:28px}
.wrap{max-width:1450px;margin:0 auto}
h1{font-size:38px;margin:0 0 6px}
.sub{font-size:23px;color:#bcd6ff;margin-bottom:25px}
.card{background:#1b2531;border:1px solid #3b4d60;border-radius:14px;padding:24px;margin:20px 0}
.ok{color:#52e67a;font-weight:bold}.bad{color:#ff6b6b;font-weight:bold}.info{color:#9ec7ff}
table{width:100%;border-collapse:collapse;font-size:20px}
th,td{text-align:left;padding:12px;border-bottom:1px solid #405064}
button{font-size:22px;padding:13px 28px;background:#2f7de1;color:#fff;border:0;border-radius:10px;cursor:pointer}
code{background:#111a22;padding:2px 6px;border-radius:4px}
.success{background:#0f4123;border:1px solid #28a858;color:#edfff3;padding:16px;border-radius:12px;font-size:24px}
.error{background:#4a1717;border:1px solid #b84646;color:#ffecec;padding:16px;border-radius:12px;font-size:19px}
</style>
</head>
<body>
<div class="wrap">
<h1>MRL Unified LP/RD Schedule Installer</h1>
<div class="sub">v001 · TESTPHP8 ONLY · NO DATABASE CHANGES</div>

<?php if ($installed): ?>
<div class="success"><?php echo h($installMessage); ?></div>
<?php endif; ?>

<?php if (!empty($errors)): ?>
<div class="error">
<strong>Preflight / install issues:</strong><br>
<?php foreach ($errors as $error): ?>
• <?php echo h($error); ?><br>
<?php endforeach; ?>
</div>
<?php endif; ?>

<div class="card">
<h2>Canonical Schedule Preflight</h2>
<p>Host: <strong><?php echo h($host !== '' ? $host : '(unknown)'); ?></strong>
— <?php echo $host === REQUIRED_HOST ? '<span class="ok">PASS</span>' : '<span class="bad">REFUSED</span>'; ?></p>
<p>Schedule: <code>/race_results/_race_results_schedule.json</code>
— <?php echo !empty($scheduleInfo) ? '<span class="ok">PASS</span>' : '<span class="bad">FAIL</span>'; ?></p>
<?php if (!empty($scheduleInfo)): ?>
<p class="info">
Source: <?php echo h($scheduleInfo['source']); ?><br>
Generated: <?php echo h($scheduleInfo['generated_at']); ?><br>
MRL points races: <?php echo h((string)$scheduleInfo['points_races']); ?>
</p>
<?php endif; ?>
</div>

<div class="card">
<h2>File Preflight</h2>
<table>
<tr><th>File</th><th>Expected</th><th>After</th><th>Status</th></tr>
<?php foreach ($targets as $label => $meta): ?>
<?php $ready = isset($prepared[$label]); ?>
<tr>
<td><?php echo h($label); ?></td>
<td><?php echo h($meta['expected']); ?></td>
<td><?php echo h($meta['after']); ?></td>
<td><?php echo $ready ? '<span class="ok">READY</span>' : '<span class="bad">NOT READY</span>'; ?></td>
</tr>
<?php endforeach; ?>
</table>
</div>

<div class="card">
<h2>What This Changes</h2>
<p style="font-size:20px;line-height:1.5">
LP and RD will both use <code>/race_results/_race_results_schedule.json</code>
for MRL points-race identity and race start times. Segment boundaries remain
DB-driven from <code>segment_race_ranges</code>. The legacy
<code>/race_results/&lt;year&gt;/_schedule.json</code> file is no longer required by LP/RD.
</p>
<p>Backup folder: <code><?php echo h(basename($backupDir)); ?></code></p>

<?php if (!$installed && empty($errors)): ?>
<form method="post">
<button type="submit" name="install_unified_schedule" value="1">Install Unified LP/RD Schedule</button>
</form>
<?php elseif ($installed): ?>
<p class="ok">Installation is complete. Proceed with the test steps provided in ChatGPT.</p>
<?php endif; ?>
</div>

<div class="card">
Installer generated 8/18/2026 4:13:00 am America/New_York.
Delete this installer from the server after testing is complete.
</div>
</div>
</body>
</html>
